// ============================================
// PAYMENT ENUMS
// ============================================

// PaymentGateway is defined in the Prisma schema and generated by @prisma/client.
// Re-export it here so service/repository code can import from one place.
export { PaymentGateway } from '@prisma/client';

/**
 * Internal payment status lifecycle
 */
export enum PaymentTransactionStatus {
  CREATED = 'CREATED', // Order created in gateway
  ATTEMPTED = 'ATTEMPTED', // User initiated payment
  AUTHORIZED = 'AUTHORIZED', // Payment authorized (captured pending)
  CAPTURED = 'CAPTURED', // Payment fully captured/completed
  FAILED = 'FAILED', // Payment failed
  REFUNDED = 'REFUNDED', // Payment refunded
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CANCELLED = 'CANCELLED', // Payment cancelled before completion
}

/**
 * PayU specific transaction statuses (from PayU postback)
 */
export enum PayUTransactionStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
  PENDING = 'pending',
}
