import { AngleType } from '../enums/angle.enum';


export const ANGLE_SEQUENCE: AngleType[] = [
    AngleType.FRONT,      // Index 0 - Already generated by try-on
    AngleType.BACK,       // Index 1 - First angle to generate
    AngleType.SIDE_LEFT,  // Index 2
    AngleType.SIDE_RIGHT, // Index 3
    AngleType.LEFT,       // Index 4
    AngleType.RIGHT,      // Index 5
];

export const GEMINI_MODEL_ID = 'gemini-2.5-flash-image';


export const GENERATION_TIMEOUT = 120000; // 120 seconds


export const INITIAL_SESSION_INDEX = 1;
