services:
  streamlit:
    build:
      context: .
    command: ["streamlit", "run", "app/main.py", "--server.port=8505", "--server.address=0.0.0.0"]
    ports:
      - "8505:8505"
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
      - ./training.csv:/app/training.csv:ro
      - ./new_data:/app/new_data:ro
      - ./fashion_collection.json:/app/fashion_collection.json:ro
      - ./collection2.json:/app/collection2.json:ro
      - ./collection2_train.json:/app/collection2_train.json:ro
      - ./collection2_test.json:/app/collection2_test.json:ro
      - ./train_image:/app/train_image:ro
      - ./testiing_image_collection:/app/testiing_image_collection:ro

    restart: unless-stopped
  fusion_api:
    build:
      context: .
    command: ["uvicorn", "app.fusion_api:app", "--host", "0.0.0.0", "--port", "8791"]
    ports:
      - "8791:8791"
    volumes:
      - ./artifacts:/app/artifacts
      - ./collection2.json:/app/collection2.json:ro
      - ./collection2_train.json:/app/collection2_train.json:ro
      - ./collection2_test.json:/app/collection2_test.json:ro
    restart: unless-stopped
