-- ============================================
-- MIGRATION: Add Refund, Return, Replacement System
-- Date: 2026-02-15
-- 
-- NOTE: This migration is now a NO-OP.
-- All enums, tables, columns, indexes, and foreign keys
-- were consolidated into 20260214000000_create_oms_tables.
-- This file is kept only to preserve migration history.
-- ============================================
