/**
 * Cloudinary Image URLs for Homepage
 * Auto-generated by scripts/upload-homepage-images.js
 * DO NOT EDIT MANUALLY
 */

const CLOUD_NAME = 'dxfxicebq';

/**
 * Build an optimized Cloudinary URL with automatic format & quality.
 * Uses f_auto (WebP/AVIF where supported) and q_auto for optimal compression.
 * The CDN caches aggressively — subsequent loads are near-instant.
 */
export function cloudinaryUrl(
  publicId: string,
  opts: { w?: number; h?: number; crop?: string; quality?: string } = {}
): string {
  const transforms: string[] = [];
  if (opts.w) transforms.push(`w_${opts.w}`);
  if (opts.h) transforms.push(`h_${opts.h}`);
  if (opts.crop) transforms.push(`c_${opts.crop}`);
  transforms.push(`q_${opts.quality || "auto:good"}`);
  transforms.push("f_auto");
  const transformStr = transforms.join(",");
  return `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/${transformStr}/${publicId}`;
}

/**
 * Build an optimized Cloudinary URL for videos.
 */
export function cloudinaryVideoUrl(
  publicId: string,
  opts: { w?: number; h?: number; crop?: string; quality?: string } = {}
): string {
  const transforms: string[] = [];
  if (opts.w) transforms.push(`w_${opts.w}`);
  if (opts.h) transforms.push(`h_${opts.h}`);
  if (opts.crop) transforms.push(`c_${opts.crop}`);
  transforms.push(`q_${opts.quality || "auto"}`);
  transforms.push("f_auto");
  const transformStr = transforms.join(",");
  return `https://res.cloudinary.com/${CLOUD_NAME}/video/upload/${transformStr}/${publicId}`;
}

/**
 * Pre-mapped homepage image public IDs.
 * Use with cloudinaryUrl() for optimized, CDN-cached delivery.
 */
export const HOMEPAGE_IMAGES = {
  /** jaipur-artisans-thread.jpg (2261×1510, 187KB) */
  jaipurArtisansThread: 'aivestire/homepage/jaipur-artisans-thread',
  /** jaipur-women-craft.jpg (2261×2265, 394KB) */
  jaipurWomenCraft: 'aivestire/homepage/jaipur-women-craft',
  /** jaipur-shop-women.jpg (2255×2043, 357KB) */
  jaipurShopWomen: 'aivestire/homepage/jaipur-shop-women',
  /** jaipur-street-mural.jpg (2261×1699, 332KB) */
  jaipurStreetMural: 'aivestire/homepage/jaipur-street-mural',
  /** jaipur-bw-embroidery.jpg (2254×1511, 199KB) */
  jaipurBwEmbroidery: 'aivestire/homepage/jaipur-bw-embroidery',
  /** jaipur-women-group.jpg (2259×1430, 317KB) */
  jaipurWomenGroup: 'aivestire/homepage/jaipur-women-group',
  /** jaipur-textile-market.jpg (2140×3197, 364KB) */
  jaipurTextileMarket: 'aivestire/homepage/jaipur-textile-market',
  /** 2222.jpeg (1086×1448, 182KB) */
  tryonRealistic: 'aivestire/homepage/tryon-realistic-2222',
  /** product-1.png (1024×1024, 139KB) */
  product1: 'aivestire/homepage/product-1',
  /** product-2.png (1024×1024, 174KB) */
  product2: 'aivestire/homepage/product-2',
  /** product-3.png (1024×1024, 42KB) */
  product3: 'aivestire/homepage/product-3',
  /** product-4.png (1024×1024, 126KB) */
  product4: 'aivestire/homepage/product-4',
  /** aura-minimal.png (1024×1024, 69KB) */
  auraMinimal: 'aivestire/homepage/aura-minimal',
  /** aura-bold.png (1024×1024, 134KB) */
  auraBold: 'aivestire/homepage/aura-bold',
  /** aura-heritage.png (1024×1024, 157KB) */
  auraHeritage: 'aivestire/homepage/aura-heritage',
  /** aura-avant-garde.png (1024×1024, 117KB) */
  auraAvantGarde: 'aivestire/homepage/aura-avant-garde',
  /** aura-minimal-saree.jpg — Indian model in ivory white silk saree */
  auraMinimalSaree: 'aivestire/homepage/aura-minimal-saree',
  /** aura-bold-saree.jpg — Indian model in teal Kanjivaram saree */
  auraBoldSaree: 'aivestire/homepage/aura-bold-saree',
  /** aura-heritage-saree.jpg — Indian model in red Banarasi saree at palace */
  auraHeritageSaree: 'aivestire/homepage/aura-heritage-saree',
  /** aura-avantgarde-saree.jpg — Indian model in mint fusion saree */
  auraAvantgardeSaree: 'aivestire/homepage/aura-avantgarde-saree',
  /** story-loom-hands.png (736×1104, 137KB) */
  storyLoomHands: 'aivestire/homepage/story-loom-hands',
  /** ai-bridge.png (1024×1024, 177KB) */
  aiBridge: 'aivestire/homepage/ai-bridge',
  /** avatar-artisan-1.png (1024×1024, 130KB) */
  avatarArtisan1: 'aivestire/homepage/avatar-artisan-1',
  /** avatar-artisan-2.png (1024×1024, 165KB) */
  avatarArtisan2: 'aivestire/homepage/avatar-artisan-2',
  /** avatar-artisan-3.png (1024×1024, 132KB) */
  avatarArtisan3: 'aivestire/homepage/avatar-artisan-3',
  /** story-balloon-girl.png (1066×1600, 212KB) */
  storyBalloonGirl: 'aivestire/homepage/story-balloon-girl',
  /** story-heritage-thread.png (1080×1350, 123KB) */
  storyHeritageThread: 'aivestire/homepage/story-heritage-thread',
  /** body-shapes-guide.png (1024×1024, 188KB) */
  bodyShapesGuide: 'aivestire/homepage/body-shapes-guide',
  /** skin-tone-guide.png (1024×1024, 75KB) */
  skinToneGuide: 'aivestire/homepage/skin-tone-guide',
  /** tryon-mockup.png (1024×1024, 199KB) */
  tryonMockup: 'aivestire/homepage/tryon-mockup',
  /** jaipur-dev.mp4 (video) */
  jaipurDevVideo: 'aivestire/homepage/jaipur-dev',
} as const;

/** Pre-built optimized URLs for direct use (auto format + quality) */
export const IMG = {
  jaipurArtisansThread: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurArtisansThread),
  jaipurWomenCraft: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurWomenCraft),
  jaipurShopWomen: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurShopWomen),
  jaipurStreetMural: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurStreetMural),
  jaipurBwEmbroidery: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurBwEmbroidery),
  jaipurWomenGroup: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurWomenGroup),
  jaipurTextileMarket: cloudinaryUrl(HOMEPAGE_IMAGES.jaipurTextileMarket),
  tryonRealistic: cloudinaryUrl(HOMEPAGE_IMAGES.tryonRealistic),
  product1: cloudinaryUrl(HOMEPAGE_IMAGES.product1),
  product2: cloudinaryUrl(HOMEPAGE_IMAGES.product2),
  product3: cloudinaryUrl(HOMEPAGE_IMAGES.product3),
  product4: cloudinaryUrl(HOMEPAGE_IMAGES.product4),
  auraMinimal: cloudinaryUrl(HOMEPAGE_IMAGES.auraMinimal),
  auraBold: cloudinaryUrl(HOMEPAGE_IMAGES.auraBold),
  auraHeritage: cloudinaryUrl(HOMEPAGE_IMAGES.auraHeritage),
  auraAvantGarde: cloudinaryUrl(HOMEPAGE_IMAGES.auraAvantGarde),
  auraMinimalSaree: cloudinaryUrl(HOMEPAGE_IMAGES.auraMinimalSaree, { w: 800, crop: 'fill' }),
  auraBoldSaree: cloudinaryUrl(HOMEPAGE_IMAGES.auraBoldSaree, { w: 800, crop: 'fill' }),
  auraHeritageSaree: cloudinaryUrl(HOMEPAGE_IMAGES.auraHeritageSaree, { w: 800, crop: 'fill' }),
  auraAvantgardeSaree: cloudinaryUrl(HOMEPAGE_IMAGES.auraAvantgardeSaree, { w: 800, crop: 'fill' }),
  storyLoomHands: cloudinaryUrl(HOMEPAGE_IMAGES.storyLoomHands),
  aiBridge: cloudinaryUrl(HOMEPAGE_IMAGES.aiBridge),
  avatarArtisan1: cloudinaryUrl(HOMEPAGE_IMAGES.avatarArtisan1),
  avatarArtisan2: cloudinaryUrl(HOMEPAGE_IMAGES.avatarArtisan2),
  avatarArtisan3: cloudinaryUrl(HOMEPAGE_IMAGES.avatarArtisan3),
  storyBalloonGirl: cloudinaryUrl(HOMEPAGE_IMAGES.storyBalloonGirl),
  storyHeritageThread: cloudinaryUrl(HOMEPAGE_IMAGES.storyHeritageThread),
  bodyShapesGuide: cloudinaryUrl(HOMEPAGE_IMAGES.bodyShapesGuide),
  skinToneGuide: cloudinaryUrl(HOMEPAGE_IMAGES.skinToneGuide),
  tryonMockup: cloudinaryUrl(HOMEPAGE_IMAGES.tryonMockup),
  jaipurDevVideo: cloudinaryVideoUrl(HOMEPAGE_IMAGES.jaipurDevVideo),
} as const;
