services:
  attribute-recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attribute-recommender
    command: ["streamlit", "run", "attribute_recommendation/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
    restart: unless-stopped
