"""
Optimized token strategy with metadata caching.
Model uses cached metadata for faster, more accurate generation.
"""

# User preferred sequence: front → back → left 45° → right 45° → left → right → cycle
# Note: front (0) is already generated by initial try-on, so sequence starts from back (1)
ANGLES = ["front", "back", "side-left", "side-right", "left", "right"]

ANGLE_DEFS = {
    "front": "0° (front view)",
    "back": "180° (back view)",
    "side-left": "45° left (front-left three-quarter view)",
    "side-right": "45° right (front-right three-quarter view)",
    "left": "90° left (full left profile)",
    "right": "90° right (full right profile)",
}

class AngleSessionManager:
    """Manages angle sequences per user+product session."""
    def __init__(self):
        # Dictionary to store angle index per session_key
        # Format: {session_key: current_index}
        self.sessions = {}
    
    def get_next_angle(self, session_key: str) -> tuple[str, int]:
        """Get the next angle for a specific session and return both angle and index."""
        # Get current index for this session (default to 0 if new session)
        idx = self.sessions.get(session_key, 0)
        
        # Get the angle at this index
        angle = ANGLES[idx % len(ANGLES)]
        
        # Increment the index for next time
        self.sessions[session_key] = idx + 1
        
        return angle, idx
    
    def reset_session(self, session_key: str):
        """Reset a session to start from side-left (index 1), since index 0 is the front view already generated."""
        self.sessions[session_key] = 1
    
    def get_current_index(self, session_key: str) -> int:
        """Get the current index for a session."""
        return self.sessions.get(session_key, 0)

# Global session manager instance
_angle_manager = AngleSessionManager()

def generate_angle_prompt(
    angle: str | None = None,
    angle_index: int | None = None,
    cached_metadata: dict | None = None,
    session_key: str | None = None,
):
    """
    Generate angle-specific prompt for image generation.
    
    Uses a SIMPLE, DIRECT approach - less is more with generative AI.
    
    Args:
        angle: Specific angle to use (if None, auto-determines from session or index)
        angle_index: Specific index in ANGLES list
        cached_metadata: Optional cached image metadata
        session_key: Optional session key for tracking angle progression
    
    Returns:
        Simple, direct prompt for angle generation
    """
    # Decide angle
    if angle is None:
        if angle_index is not None:
            angle = ANGLES[angle_index % len(ANGLES)]
        elif session_key:
            angle, angle_index = _angle_manager.get_next_angle(session_key)
        else:
            angle = "front"

    angle_instruction = ANGLE_DEFS.get(angle, angle)

    # SIMPLE PROMPT - FACE-FIRST approach since model preserves clothes well
    # Background: If input has plain/white bg, generate nice fashion studio background
    # If input already has styled bg, preserve it
    prompt = (
        f"FACE PRESERVATION IS THE #1 PRIORITY.\n\n"
        
        f"This photo shows a specific person. Generate a {angle_instruction} view of THIS EXACT PERSON.\n\n"
        
        f"FACE REQUIREMENTS (CRITICAL):\n"
        f"- Copy the EXACT face from the input image\n"
        f"- Same facial structure, same eyes, same nose, same lips, same jawline\n"
        f"- Same skin color and complexion - do not lighten or darken\n"
        f"- Same eyebrows, same forehead shape\n"
        f"- If there are any facial marks or features, keep them\n\n"
        
        f"PRESERVE EXACTLY:\n"
        f"- Same hair color and style\n"
        f"- Same clothes with exact colors and patterns\n"
        f"- Full body visible, no zoom\n\n"
        
        f"BACKGROUND INSTRUCTIONS:\n"
        f"- If the input has a plain/white/simple background: Create a beautiful, professional fashion photography studio background with soft gradient lighting\n"
        f"- If the input already has a styled/designed background: Keep the SAME background exactly as shown\n"
        f"- Background should complement the clothing colors\n\n"
        
        f"CAMERA: Rotate to {angle_instruction}. Person identity and clothes stay EXACTLY the same."
    )
    return prompt
