services:
- type: web
  name: "model-demo"
  pythonVersion: 3.11
  rootDir: APP3005
  env: python
  buildCommand: pip install -r requirements.txt
startCommand: streamlit run ModelDemo/app.py --server.port $PORT --server.address 0.0.0.0
