version: '3.8'
services:
  backend:
    build:
      context: ./aivestire-backend-tmp
    container_name: nest-server
    env_file:
      - ./aivestire-backend-tmp/.env
    ports:
      - "3002:3000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aivestire
    ports:
      - "5538:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
